name: Translate lesson html files
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'
      - name: Prepare translation directory
        run: |
          rm -rf es
          cp -r $PWD /tmp/es
          mv /tmp/es .
        shell: bash
      - name: DeepL Translate Github Action
        uses: lyqht/deepl-translate-github-action@v2
        with:
          target_languages: es
          input_file_path: ./01-intro.html
          output_file_name_pattern: ./{language}/01-intro.html
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
